### ISSUE TITLE
Publishing artifacts to Maven Central affected by "OSSRH service will reach end-of-life on June 30th, 2025"

### ISSUE THREAD

**Issue by timtebeek** [moderneinc/gh-automation#104]
Saw this message logging in to https://oss.sonatype.org/#welcome
> The OSSRH service will reach end-of-life on [June 30th, 2025](https://central.sonatype.org/news/20250326_ossrh_sunset/). Learn more about how to transfer to the Central Publishing Portal [here](https://central.sonatype.org/faq/what-is-different-between-central-portal-and-legacy-ossrh/#process-to-migrate).

It also affects https://github.com/openrewrite/gh-automation/, but figured log the issue here as that's a) private, and b) shows on our project board.

EDIT JENTE: 
I think it would be:

#### prepare
- [x] Create new token(s) (SONATYPE_USERNAME & SONATYPE_TOKEN) to be used througout the GHA on [central.sonatype](https://central.sonatype.com/account) and create the necessary secrets. It seems that we do not have a token for central atm (going through the secrets of both org OR and Moderne). In that case it is safe to do this action first and already preconfigure the secrets.
- [x] Add the new repository to [the cli](https://github.com/moderneinc/moderne-cli/blob/66d1f2519f456edaecaf0d8030628e6d48bc5b00/core/core/src/main/java/io/moderne/cli/config/ArtifactRepository.java#L76-L84) (as first?) for default snapshot resolution to `https://central.sonatype.com/repository/maven-snapshots/`

~Release train~
~Release all the modules as usual (except plugin)~
This is no longer possible

#### plugin
- [x] small change in the [plugins](https://github.com/openrewrite/rewrite-build-gradle-plugin/blob/d15d687617f65c5285bc55f15067f8fae4d59179/src/main/java/org/openrewrite/gradle/RewriteDependencyRepositoriesPlugin.java#L31)
- [x] Update the rewrite version in the plugin to the just released version
- [x] Release the plugin
I think this should be a major semver bump of the plugins as the authentication changed to use different publishing tokens (hence breaking if people do not change their publish token)

#### Namespace migration:
- [x] [Self migration should be possible](https://central.sonatype.org/faq/what-is-different-between-central-portal-and-legacy-ossrh/#self-service-migration)
- [x] [Enable snapshots for the migrated namespaces](https://central.sonatype.org/publish/publish-portal-snapshots/#enabling-snapshot-releases-for-your-namespace)

#### Replace repositories in repositories.
- [ ] remove the oss / s01.oss snapshot resolution from [the cli](https://github.com/moderneinc/moderne-cli/blob/66d1f2519f456edaecaf0d8030628e6d48bc5b00/core/core/src/main/java/io/moderne/cli/config/ArtifactRepository.java#L76-L84) for default snapshot resolution to `https://central.sonatype.com/repository/maven-snapshots/`
- [ ] Run the recipe (merge the [gh-automation](https://github.com/openrewrite/gh-automation) changes first!): 
```yaml
recipeList:
  - org.openrewrite.yaml.ChangeKey:
      oldKeyPath: $..ossrh_username
      newKey: sonatype_username
      filePattern: **.y*ml
  - org.openrewrite.yaml.ChangeKey:
      oldKeyPath: $..ossrh_token
      newKey: sonatype_token
      filePattern: **.y*ml
  - org.openrewrite.text.FindAndReplace:
      find: secrets.OSSRH_USERNAME
      replace: secrets.SONATYPE_USERNAME
      filePattern: **.y*ml
  - org.openrewrite.text.FindAndReplace:
      find: secrets.OSSRH_TOKEN
      replace: secrets.SONATYPE_TOKEN
      filePattern: **.y*ml
  - org.openrewrite.text.FindAndReplace:
      find: http(s)?://s01.oss.sonatype.org/content/repositories/snapshots(/)?
      replace: http$1://central.sonatype.com/repository/maven-snapshots$2
      regex: "True"
      caseSensitive: "True"
  - org.openrewrite.text.FindAndReplace:
      find: http(s)?://oss.sonatype.org/content/repositories/snapshots(/)?
      replace: http$1://central.sonatype.com/repository/maven-snapshots$2
      regex: "True"
      caseSensitive: "True"
```

#### Cleanup
- [ ] OSSRH_TOKEN and OSSRH_USERNAME should have no usages anymore so can be removed.

Now, important to note that the "protocol" has changed and gradle's maven-publish is actually not the recommended way of using this as listed [here](https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/#publishing-by-using-the-portal-ossrh-staging-api). Should we try to migrate to the new service over time with our plugin? Gradle has [no intention of supporting](https://github.com/gradle/gradle/issues/28120) this custom protocol themselves as part of maven-publish, it seems. 
> We hope that over time plugins will adopt the [Portal API](https://central.sonatype.org/publish/publish-portal-api/) rather than rely on this service.

Also I do not think we have to adapt the singing related values (e.g. ossrh_signing_key) as they do not really have anything to do with snapshot repo location. Only pity that their name refers to ossrh. 

The platform is also downloading snapshot version -> should that also be updated or is that automatically?
